baseURL = "/hugo-website"
languageCode = "zh-cn"
title = "Rabbit&Carrot"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Huis"
    description = "Personal blog"
    githubUsername = "hui1hui2hui3"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "" # "KorinnaCTT" # should match the name on webfonts.ffonts.net Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "java", "javascript", "scala", "swift", "python"]
	walineDomain="myblog-waline-5cpzcds7x-hui1hui2hui3-gmailcom"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

##[[menu.main]]
    ##url = "/project/"
    ##name = "Projects"
    ##weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

##[[menu.icon]]
    #url = "mailto:test@test.com"
    #name = "fas fa-envelope"
    #weight = 1

[[menu.icon]]
    url = "https://github.com/hui1hui2hui3/"
    name = "fab fa-github"
    weight = 1

##[[menu.icon]]
    #text = "raandca"
    #name = "fab fa-weixin"
    #weight = 3

##[[menu.icon]]
    #url = "https://www.linkedin.com/in/username/"
    #name = "fab fa-linkedin"
    #weight = 4

##[[menu.icon]]
    #url = "https://www.stackoverflow.com/username/"
    #name = "fab fa-stack-overflow"
    #weight = 5
